POST http://localhost:19090/api/generation-settings
Content-Type: application/json

{
  "model": {
    "aggregateSettings": [
      {
        "aggregateName": "Account",
        "stateFields": [
          {
            "name": "id",
            "type": "String"
          },
          {
            "name": "creditLimit",
            "type": "double"
          },
          {
            "name": "creditLimitThreshold",
            "type": "double"
          },
          {
            "name": "description",
            "type": "String"
          }
        ],
        "events": [
          {
            "name": "AccountOpened",
            "fields": [
              "id"
            ]
          },
          {
            "name": "CreditLimitChanged",
            "fields": [
              "id",
              "creditLimit",
              "creditLimitThreshold"
            ]
          }
        ],
        "methods": [
          {
            "name": "open",
            "useFactory": "true",
            "parameters": [
              "creditLimitThreshold"
            ],
            "event": "AccountOpened"
          },
          {
            "name": "updateCreditLimit",
            "useFactory": "false",
            "parameters": [
              "creditLimit",
              "creditLimitThreshold"
            ],
            "event": "CreditLimitChanged"
          }
        ],
        "api": {
          "rootPath": "accounts",
          "routes": [
            {
              "path": "",
              "httpMethod": "POST",
              "aggregateMethod": "open",
              "requireEntityLoad": "false"
            },
            {
              "path": "/accounts/{id}/credit-limits",
              "httpMethod": "PATCH",
              "aggregateMethod": "updateCreditLimit",
              "requireEntityLoad": "true"
            }
          ]
        }
      }
    ],
    "persistenceSettings": {
      "storageType": "STATE_STORE",
      "useCQRS": "true",
      "projections": "EVENT_BASED",
      "database": "IN_MEMORY",
      "commandModelDatabase": "IN_MEMORY",
      "queryModelDatabase": "IN_MEMORY"
    }
  },
  "context": {
    "xoomVersion": "1.4.1-SNAPSHOT",
    "groupId": "io.vlingo",
    "artifactId": "banking",
    "artifactVersion": "1.0.0",
    "packageName": "io.vlingo.banking"
  },
  "deployment": {
    "type": "NONE",
    "dockerImage": "",
    "kubernetesImage": "",
    "kubernetesPod": "",
    "clusterNodes": 0
  },
  "useAnnotations": true,
  "useAutoDispatch": false,
  "projectDirectory": "D:\\projects"
}

###
